### PR TITLE
qmanager: Asynchronously communicate with resource in the scheduling loop to allow job updates while matching

### LINKED ISSUE #1222: submitting a large number of jobs and canceling them caused scheduler "hang"
On elcap a user submitted a large number of jobs, each requesting a specific node, then thought better of it and canceled them all. For the past few hours the scheduler has not scheduled any jobs and the "alloc pending" count is stuck at many thousands.

Attempting to stop the queues has not improved the situation.

On the recommendation of @trws I've grabbed a core of the rank 0 broker (available in my homedir).

Here's the resource module stats at the time of this failure:
```json
{
 "match": {
  "succeeded": {
   "njobs": 11940,
   "njobs-reset": 11940,
   "max-match-jobid": 429461867754015744,
   "max-match-iters": 52,
   "stats": {
    "min": 0.001353974,
    "max": 32.755777653999999,
    "avg": 0.29216099639715115,
    "variance": 3.2035476969734025
   }
  },
  "failed": {
   "njobs": 83916,
   "njobs-reset": 83916,
   "max-match-jobid": 429655446928752640,
   "max-match-iters": 328,
   "stats": {
    "min": 0.0073356740000000004,
    "max": 68.145720294,
    "avg": 0.29968277191067089,
    "variance": 0.886960191744261
   }
 }
```

The use case here is that a user is looking for bad/slow nodes and needs to run a test on each node in a queue. For now I've suggested they allocate all the nodes from the queue and then use bulksubmit in that subinstance, which should work better.

### PR DESCRIPTION
**Pull request by trws**
This is a replacement for #1226, though it doesn't yet have eager cancellation of the sched loop to immediately process job cancellations. The short version is that this makes our backfill queues completely asynchronous with respect to the resource module, and deals with the 10,000 allocs followed by 10,000 cancels test in about 45 seconds on my laptop. Assuming the numbers are comparable, that's a bit under 100x faster than the time @milroy reported for the test in #1222.

This also _completely_ changes the performance profile of flux under this kind of load.  During a flood of requests like that, match still shows up as something like 30%, but that's all.  The job-injest and qmanager modules rise to almost match it for consumption, and the yaml processing becomes a meaningful cost.  May look and see if some of that can be easily squashed out.

fixes #1222

### CODE REVIEW

**Review by grondo — COMMENTED** [review]
This sounds great! Unfortunately, I'm not familiar enough with the code to do a proper review, but I didn't notice any glaring issues. It would probably be good to get @milroy to rerun his workload on this branch and report back (and do a code review).

But wow, great improvement.

**Comment by trws** [comment]
I forgot to base this on the reconsider fix, that should fix the hangs in the unreservable test we got on bookworm and jammy before.

**Comment by trws** [comment]
Found another reconsider bug that caused the qmanager to spin after making it async like this.  Added fix here.

**Comment by trws** [comment]
Aaaand clearly that did not work. Trying to track down the core issue here.

**Comment by trws** [comment]
Fun new facts, this _did_ work, but there's an ordering bug that's exposed by this linked above.  Once that lands, this should be all green, and no longer spins.  I would recommend any side testing with this branch to be done with the flux-core change in flux-framework/flux-core#6062 in case you're looking @milroy.

**Comment by milroy** [comment]
I can confirm the 100x speedup on my test scripts. I'm seeing runtimes of 47-53s now.

**Comment by milroy** [comment]
I can also confirm successful test results with the change here: https://github.com/flux-framework/flux-core/pull/6062.

However, `ctest` is taking 59s in comparison with 37s on Fluxion `master`.

**Comment by trws** [comment]
That's interesting, I suppose it's not entirely surprising since there's longer latency between a response from resource and processing it, but that's much more of a hit than I expected. Will try to get a perf trace and see what's changed.

**Comment by trws** [comment]
Are your measurements using the same version of flux-core @milroy? When I run a master fluxion vs this PR, I get the same perf for both, but they're both built against the flux-core PR.

**Comment by trws** [comment]
Good news everyone! (if you didn't read this in Farnsworth's voice, feel free to do so now 😉 )

The merged PR upstream fixed all the failures here with no further touching at all.  @milroy is there anything further you'd like so see or tweak here?

**Comment by grondo** [comment]
Excellent! Can you suggest a PR title that would translate to a good line in the release notes? (release notes are semi-automated with a script, and each PR ends up as a line noted by title).

**Comment by trws** [comment]
Updated, feel free to tweak if you like.

File: qmanager/policies/base/queue_policy_base.hpp [hunk 1]
```diff
@@ -865,6 +865,7 @@ class queue_policy_base_t : public resource_model::queue_adapter_base_t
 
     int process_provisional_reprio ()
     {
+        bool reprioritezed_a_job = false;
```
Comment (jameshcorbett) [inline qmanager/policies/base/queue_policy_base.hpp:868]: typo in variable name: `reprioritized`

File: qmanager/policies/queue_policy_bf_base_impl.hpp [hunk 2]
```diff
@@ -47,6 +49,38 @@ int queue_policy_bf_base_t<reapi_type>::cancel_reserved_jobs (void *h)
...
+    std::unique_ptr<char, decltype (_free)>  jobs_str (
+            json_dumps (jobarray.get(), JSON_INDENT (0)),
+            _free
+            );
+    if ( !jobs_str) {
+        errno = ENOMEM;
+        return -1;
+    }
+    int res = reapi_type::match_allocate_multi (m_handle, m_try_reserve, jobs_str.get (), this);
+    return res;
```
Comment (jameshcorbett) [inline qmanager/policies/queue_policy_bf_base_impl.hpp:81]: combine these lines?

**Review by jameshcorbett — COMMENTED** [review]
I don't know the qmanager code base very well so my comments are just two superficial things I noticed.

**Comment by trws** [comment]
I just found that this needs another patch.  It's "correct" in that it stops the spinning and gives us the async behavior, but it doesn't process jobs past queue-depth because of fixing the spinning issue. Patch coming shortly.

**Comment by trws** [comment]
Ok, the patch is up, but as you can see it changes the queue-depth behavior.  Turns out fixing this issue brings us back there.  I'm going to fix the test at this point, and will explain this in the commit message as well, but here's what's going on.  The code we have doesn't re-enter the sched loop unless an event has occurred, and the test encodes this behavior and expects that _exactly one_ sched loop will happen after a job is cancelled.  With the new code, because something has been scheduled and there are jobs that haven't been considered, we start a new scheduling loop to try and get more work done immediately, as a result we process and start a job that sched used to think was "past queue depth" because it isn't past the queue depth on the second loop.

**Comment by trws** [comment]
Pushed, I'm sorry for the last minute churn here, but in working on the benchmark for my next PR (to help deal with the many-time-points issue) I realized that this one essentially hung trying to run it once I sped up the job submission enough.  Either way, this one should be ready to go, other one coming shortly.

**Comment by milroy** [comment]
@trws I don't think I was using the same versions of flux-core in the two setups for my previous tests. I'm now seeing very similar execution times between Fluxion master and this PR. Note that the `ctest` times have increased by almost a factor of 2 recently.

**Comment by trws** [comment]
I'll try to figure out why that is, clearly not a good thing.  As soon as I get the failed-job match time PR up I'll try to bisect for it.

File: qmanager/policies/queue_policy_bf_base.hpp [hunk 3]
```diff
@@ -27,19 +27,25 @@ class queue_policy_bf_base_t : public queue_policy_base_t
...
 
 protected:
     unsigned int m_reservation_depth;
     unsigned int m_max_reservation_depth = MAX_RESERVATION_DEPTH;
 
 private:
+    int next_match_iter ();
     int cancel_completed_jobs (void *h);
     int cancel_reserved_jobs (void *h);
     int allocate_orelse_reserve_jobs (void *h, bool use_alloced_queue);
```
Comment (milroy) [inline qmanager/policies/queue_policy_bf_base.hpp:42]: Looks like `use_alloced_queue` is vestigial here.

File: qmanager/policies/queue_policy_bf_base_impl.hpp [hunk 4]
```diff
@@ -47,6 +49,37 @@ int queue_policy_bf_base_t<reapi_type>::cancel_reserved_jobs (void *h)
...
+    if ( !jobs_str) {
+        errno = ENOMEM;
+        return -1;
+    }
+    return reapi_type::match_allocate_multi (m_handle, m_try_reserve, jobs_str.get (), this);
+}
+
 template<class reapi_type>
 int queue_policy_bf_base_t<reapi_type>::allocate_orelse_reserve_jobs (void *h,
                                                                       bool use_alloced_queue)
```
Comment (milroy) [inline qmanager/policies/queue_policy_bf_base_impl.hpp:92]: Looks like `use_alloced_queue` is disused.

**Review by milroy — APPROVED** [review]
I found some formatting nits, and a disused variable.

Apart from that this looks good to me. Really impressive speedup!

File: qmanager/policies/queue_policy_bf_base.hpp (hunk 3 above)
Comment (trws) [reply qmanager/policies/queue_policy_bf_base.hpp:42]: It is, and as far as I know has been for a while.

File: qmanager/policies/queue_policy_bf_base_impl.hpp [hunk 5]
```diff
@@ -47,6 +49,37 @@ int queue_policy_bf_base_t<reapi_type>::cancel_reserved_jobs (void *h)
...
+    }
+    auto _free = [](char *p) { free (p); };
+    std::unique_ptr<char, decltype (_free)>  jobs_str (
+            json_dumps (jobarray.get(), JSON_INDENT (0)),
+            _free
+            );
+    if ( !jobs_str) {
+        errno = ENOMEM;
+        return -1;
+    }
```
[the remark this answers is not in the document]
Comment (trws) [reply qmanager/policies/queue_policy_bf_base_impl.hpp:86]: Good point, I've split that up to help it flow a little better.
