### PR TITLE
Dense resource type with DoS protection

### LINKED ISSUE #1298: fluxion crash in 10% of user runs on elcap
On elcap a user is running a series of jobs that appear to cause a Fluxion crash roughly 10% of the time. We have one corefile (in my homedir under `fluxion-crash`). I believe this is still occurring for one or two users, so we'll want to determine how to get a patch for this specific issue to apply to the current flux-sched RPM asap.

@trws took a look and reported:
> Ok, this is down in the resource_type_t string freeing cleanup logic. If nothing else, the in progress PR to make the dense storage backend work for resource type would make this particular failure mode impossible.

Here's the backtrace:
```gdb
#0  0x00001555526c1c30 in std::_Hash_bytes(void const*, unsigned long, unsigned long) () from /lib64/libstdc++.so.6
#1  0x000015555553be45 in std::_Hash_impl::hash (__seed=3339675911, 
    __clength=<optimized out>, __ptr=<optimized out>)
    at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/functional_hash.h:206
#2  std::hash<std::basic_string_view<char, std::char_traits<char> > >::operator() (__str=..., this=<optimized out>)
    at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/string_view:698
#3  intern::detail::string_hash::operator() (str=..., this=0x754c50)
    at /builddir/build/BUILD/flux-sched-0.38.0/src/common/libintern/interner.cpp:40
#4  std::__detail::_Hash_code_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, intern::detail::sparse_string_node>, std::__detail::_Select1st, intern::detail::string_hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, true>::_M_hash_code (
    __k=..., this=0x754c50)
    at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/hashtable_policy.h:1270
#5  std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, intern::detail::sparse_string_node>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, intern::detail::sparse_string_node> >, std::__detail::_Select1st, std::equal_to<void>, intern::detail::string_hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_erase (
    __k=..., this=0x754c50)
    at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/hashtable.h:2360
#6  std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, intern::detail::sparse_string_node>, std::--Type <RET> for more, q to quit, c to continue without paging--c
allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, intern::detail::sparse_string_node> >, std::__detail::_Select1st, std::equal_to<void>, intern::detail::string_hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::erase (__k=..., this=0x754c50) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/hashtable.h:973
#7  std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, intern::detail::sparse_string_node, intern::detail::string_hash, std::equal_to<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, intern::detail::sparse_string_node> > >::erase (__x=..., this=0x754c50) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/unordered_map.h:763
#8  intern::detail::remove_rc (storage=0x754c40, s=<optimized out>) at /builddir/build/BUILD/flux-sched-0.38.0/src/common/libintern/interner.cpp:93
#9  0x000015555553d652 in std::_Sp_counted_deleter<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*), std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=<optimized out>) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/shared_ptr_base.h:526
#10 0x0000155540121b76 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x1554f8945930) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/shared_ptr_base.h:354
#11 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x1554f8945930) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/shared_ptr_base.h:317
#12 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x1554f964ea40, __in_chrg=<optimized out>) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/shared_ptr_base.h:1071
#13 std::__shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x1554f964ea38, __in_chrg=<optimized out>) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/shared_ptr_base.h:1524
#14 std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>::~shared_ptr (this=0x1554f964ea38, __in_chrg=<optimized out>) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/shared_ptr.h:175
#15 intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >::~interned_string (this=0x1554f964ea38, __in_chrg=<optimized out>) at /builddir/build/BUILD/flux-sched-0.38.0/src/common/libintern/interner.hpp:162
#16 Flux::resource_model::detail::evals_t::~evals_t (this=0x1554f964ea10, __in_chrg=<optimized out>) at /builddir/build/BUILD/flux-sched-0.38.0/resource/evaluators/edge_eval_api.cpp:95
#17 0x000015554011d427 in std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t>::~pair (this=0x1554f964ea00, __in_chrg=<optimized out>) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_pair.h:185
#18 std::destroy_at<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > (__location=0x1554f964ea00) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_construct.h:88
#19 std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > > >::destroy<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > (__p=0x1554f964ea00, __a=...) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/alloc_traits.h:537
#20 std::_Rb_tree<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t>, std::_Select1st<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> >, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > >::_M_destroy_node (__p=0x1554f964e9e0, this=<optimized out>) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_tree.h:623
#21 std::_Rb_tree<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t>, std::_Select1st<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> >, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > >::_M_drop_node (this=<optimized out>, __p=0x1554f964e9e0) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_tree.h:631
#22 std::_Rb_tree<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t>, std::_Select1st<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> >, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > >::_M_erase (this=<optimized out>, __x=0x1554f964e9e0) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_tree.h:1937
#23 std::_Rb_tree<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t>, std::_Select1st<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> >, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > >::~_Rb_tree (this=0x1555205d1ad8, __in_chrg=<optimized out>) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_tree.h:984
#24 std::map<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, Flux::resource_model::detail::evals_t, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > >::~map (this=0x1555205d1ad8, __in_chrg=<optimized out>) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_map.h:312
#25 boost::container::allocator_traits<boost::container::small_vector_allocator<boost::container::new_allocator<std::map<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, Flux::resource_model::detail::evals_t, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > > > > >::priv_destroy<std::map<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, Flux::resource_model::detail::evals_t, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > > > (p=0x1555205d1ad8) at /usr/include/boost/container/allocator_traits.hpp:394
#26 boost::container::allocator_traits<boost::container::small_vector_allocator<boost::container::new_allocator<std::map<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, Flux::resource_model::detail::evals_t, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > > > > >::destroy<std::map<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, Flux::resource_model::detail::evals_t, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > > > (p=0x1555205d1ad8, a=...) at /usr/include/boost/container/allocator_traits.hpp:322
#27 boost::container::destroy_alloc_n<boost::container::small_vector_allocator<boost::container::new_allocator<std::map<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, Flux::resource_model::detail::evals_t, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > > > >, std::map<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, Flux::resource_model::detail::evals_t, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > >*, unsigned long> (n=0, f=0x1555205d1ad8, a=...) at /usr/include/boost/container/detail/copy_move_algo.hpp:960
#28 boost::container::vector<std::map<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, Flux::resource_model::detail::evals_t, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > >, boost::container::small_vector_allocator<boost::container::new_allocator<std::map<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, Flux::resource_model::detail::evals_t, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > > > > >::~vector (this=0x1555205d1ac0, __in_chrg=<optimized out>) at /usr/include/boost/container/vector.hpp:1018
#29 boost::container::small_vector_base<std::map<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, Flux::resource_model::detail::evals_t, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > >, boost::container::new_allocator<std::map<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, Flux::resource_model::detail::evals_t, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > > > >::~small_vector_base (this=0x1555205d1ac0, __in_chrg=<optimized out>) at /usr/include/boost/container/small_vector.hpp:323
#30 boost::container::small_vector<std::map<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, Flux::resource_model::detail::evals_t, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > >, 2ul, boost::container::new_allocator<std::map<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, Flux::resource_model::detail::evals_t, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > > > >::~small_vector (this=0x1555205d1ac0, __in_chrg=<optimized out>) at /usr/include/boost/container/small_vector.hpp:473
#31 intern::interned_key_vec<intern::interned_string<intern::dense_storage<Flux::resource_model::subsystem_tag, unsigned char> >, std::map<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> >, Flux::resource_model::detail::evals_t, std::less<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > >, std::allocator<std::pair<intern::interned_string<intern::rc_storage<Flux::resource_model::resource_type_tag> > const, Flux::resource_model::detail::evals_t> > >, 2>::~interned_key_vec (this=0x1555205d1ac0, __in_chrg=<optimized out>) at /builddir/build/BUILD/flux-sched-0.38.0/src/common/libintern/interner.hpp:323
#32 Flux::resource_model::scoring_api_t::~scoring_api_t (this=0x1555205d1ac0, __in_chrg=<optimized out>) at /builddir/build/BUILD/flux-sched-0.38.0/resource/evaluators/scoring_api.cpp:35
#33 0x00001555400f66fd in Flux::resource_model::detail::dfu_impl_t::dom_dfv (this=<optimized out>, meta=..., u=<optimized out>, resources=..., pristine=<optimized out>, excl=0x1555205d1beb, to_parent=...) at /builddir/build/BUILD/flux-sched-0.38.0/resource/traversers/dfu_impl.cpp:765
#34 0x00001555400f7206 in Flux::resource_model::detail::dfu_impl_t::select (this=this@entry=0x1554f8004e80, j=..., root=root@entry=0, meta=..., excl=excl@entry=false) at /builddir/build/BUILD/flux-sched-0.38.0/resource/traversers/dfu_impl.cpp:1165
#35 0x00001555400ea9ff in Flux::resource_model::dfu_traverser_t::schedule (this=0x1554f8004e80, jobspec=..., meta=..., x=<optimized out>, op=MATCH_ALLOCATE_W_SATISFIABILITY, root=0, dfv=std::unordered_map with 2 elements = {...}) at /builddir/build/BUILD/flux-sched-0.38.0/resource/traversers/dfu.cpp:157
#36 0x00001555400eb4be in Flux::resource_model::dfu_traverser_t::run (this=this@entry=0x1554f8004e80, jobspec=..., writers=std::shared_ptr<Flux::resource_model::match_writers_t> (use count 1, weak count 0) = {...}, op=op@entry=MATCH_ALLOCATE_W_SATISFIABILITY, jobid=jobid@entry=554956750848, at=at@entry=0x1555205d2278) at /builddir/build/BUILD/flux-sched-0.38.0/resource/traversers/dfu.cpp:380
#37 0x00001555400c055b in run (ctx=std::shared_ptr<resource_ctx_t> (use count 2, weak count 0) = {...}, jobid=554956750848, cmd=0x1554f801d8d0 "allocate_with_satisfiability", jstr=..., at=0x1555205d2278, errp=0x0) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/shared_ptr_base.h:1665
#38 0x00001555400c2265 in run_match (ctx=std::shared_ptr<resource_ctx_t> (use count 2, weak count 0) = {...}, jobid=554956750848, cmd=0x1554f801d8d0 "allocate_with_satisfiability", jstr="{\"resources\":[{\"type\":\"node\",\"count\":4,\"exclusive\":true,\"with\":[{\"type\":\"slot\",\"count\":4,\"with\":[{\"type\":\"core\",\"count\":1},{\"type\":\"gpu\",\"count\":1}],\"label\":\"task\"}]}],\"tasks\":[{\"command\":[\"../../../."..., now=now@entry=0x1555205d2280, at=at@entry=0x1555205d2278, overhead=0x1555205d2288, o=..., errp=0x0) at /builddir/build/BUILD/flux-sched-0.38.0/resource/modules/resource_match.cpp:1749
#39 0x00001555400cb5e4 in match_multi_request_cb (h=0x1554f8000be0, w=<optimized out>, msg=0x1554f0009c80, arg=<optimized out>) at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/new_allocator.h:80
#40 0x00001555550c261a in call_handler (mh=0x1554f80055f0, msg=msg@entry=0x1554f0009c80) at msg_handler.c:344
#41 0x00001555550c2c4b in dispatch_message (type=1, msg=0x1554f0009c80, d=0x1554f80031f0) at msg_handler.c:380
#42 handle_cb (r=0x1554f8002800, hw=<optimized out>, revents=<optimized out>, arg=0x1554f80031f0) at msg_handler.c:481
#43 0x00001555550eb903 in ev_invoke_pending (loop=0x1554f8002820) at ev.c:3770
#44 0x00001555550ef9a8 in ev_run (flags=0, loop=0x1554f8002820) at ev.c:4190
#45 ev_run (loop=0x1554f8002820, flags=0) at ev.c:4021
#46 0x00001555550c19ef in flux_reactor_run (r=0x1554f8002800, flags=<optimized out>) at reactor.c:124
#47 0x00001555400cc793 in mod_main (h=0x1554f8000be0, argc=<optimized out>, argv=<optimized out>) at /builddir/build/BUILD/flux-sched-0.38.0/resource/modules/resource_match.cpp:3021
#48 0x000000000041170f in module_thread (arg=0x755a20) at module.c:225
#49 0x0000155554e861ca in start_thread () from /lib64/libpthread.so.0
#50 0x000015555371e8d3 in clone () from /lib64/libc.so.6
```

### PR DESCRIPTION
**Pull request by trws**
I'm still debating this change to be honest.  The refcounted strings for resource types are showing up as a meaningful cost in comparisons and refcounting, it's not terrible but it's also not great.  This solves the issue by making it so that dense storage interners have a notion of being "final" or placed in a state where new strings can't be added anymore. It also adds an interface to "open" a finalized interner for updates, on a per-thread basis, so that we can do things like database updates. To my surprise, this passed all but one of our tests without re-opening the interners, and that last one by re-opening them in update_resource.

The upside is that after this change, and without using it to optimize any of the type maps or anything like that, we get another 20-30% improvement in throughput for some of my tests.  I've seen as much as 250 jobs/s.  The downside is that the interface is a little bit odd for this, and at the moment the only way we have to signal the thing is closed is to throw an exception.  Given that the only source of new resource types after init should be jobspec though, which already throws exceptions for any parse errors (which is basically what this would be, if the resource type doesn't exist it can't match) I'm not sure how bad that is. Would love input on this.  Might be easier to use if it worked with a lock/unlock pair so lock_guard would work, not sure.

I _think_ this
fixes #1298

### CODE REVIEW

**Comment by trws** [comment]
@garlick, @jameshcorbett, @milroy, have a look at this.  The code path that causes the crash in #1298 should be completely gone, and it should make things both faster and a bit more self-validating since we'll catch unknown resource types at jobspec parsing time rather than later.  Unfortunately I haven't been able to repro the issue from #1298, and my attempts to get onto elcap to do it have been foiled by some really gnarly latency from Perth (at pawsey it's sometimes 5 seconds to see a character in ssh 😬 ).  If someone could give it a poke and verify I'd really appreciate it.

File: resource/libjobspec/jobspec.cpp [hunk 1]
```diff
@@ -126,7 +126,13 @@ Resource::Resource (const YAML::Node &resnode)
...
         throw parse_error (resnode["type"], "Value of \"type\" must be a scalar");
     }
-    type = resource_model::resource_type_t{resnode["type"].as<std::string> ()};
+    try {
+        type = resource_model::resource_type_t{resnode["type"].as<std::string> ()};
+    } catch (std::system_error e) {
+        // resource_type must be closed or full
+        throw parse_error (resnode["type"],
+                           "Value of \"type\" must be a resource type known to fluxion");
+    }
```
Comment (jameshcorbett) [inline resource/libjobspec/jobspec.cpp:135]: This change goes along with the test change right? Maybe these two changes could be their own commit?

File: t/t4001-match-allocate.t [hunk 2]
```diff
@@ -56,6 +56,11 @@ test_expect_success 'handling of a malformed jobspec works' '
     test_expect_code 2 flux ion-resource match allocate ${malform}
 '
 
+test_expect_success 'handling of an invalid resource type works' '
+    test_expect_code 1 flux ion-resource match allocate \
+        "${SHARNESS_TEST_SRCDIR}/data/resource/jobspecs/basics/bad_res_type.yaml"
```
Comment (jameshcorbett) [inline t/t4001-match-allocate.t:61]: Any way to check for the specific error message?

**Review by jameshcorbett — APPROVED** [review]
I think this looks reasonable, what does testing it out on elcap look like? ie what would I need to do

**Comment by trws** [comment]
> I think this looks reasonable, what does testing it out on elcap look like? ie what would I need to do

I'm not 100% sure other than build it and run some bulksubmit jobs. @grondo did you ever manage to repro it?

File: resource/libjobspec/jobspec.cpp (hunk 1 above)
Comment (trws) [reply resource/libjobspec/jobspec.cpp:135]: This is ensuring that the failure gets converted to a parse error, otherwise it gets handled like something completely else and several existing tests fail. I could group them up but it would leave a commit that can't pass.

File: t/t4001-match-allocate.t (hunk 2 above)
Comment (trws) [reply t/t4001-match-allocate.t:61]: Not here, but that's a good point. I should be able to add a resource_query test that can check for the parse error and that it comes from the resource type specifically.

**Comment by grondo** [comment]
I was never able to reproduce it. It seemed to occur 10% of the time at 128 nodes. The jobspec and batch script are in my homedir at `fluxion-crash`.
