### PR TITLE
Fix an integer overflow bug etc.

### LINKED ISSUE #932: Successful match is policy dependent
During KubeFlux testing, I discovered that for a given jobspec `lonode` and `hinode` policies do not return a successful match, while `low` and `high` do.  Furthermore, `hinode` and `lonode` match behavior is inconsistent with expectation.

Here's the zipped JGF from a 16 `hpc6a` node AWS EKS cluster: [cluster.json.zip](https://github.com/flux-framework/flux-sched/files/8499108/cluster.json.zip), and the test jobspec that requests all cluster cores (`test.yaml`): 
```YAML
version: 9999
resources:
- type: slot
  count: 16
  label: default
  with:
  - type: core
    count: 94
attributes:
  system:
    duration: 3600
tasks:
- command: [""]
  slot: default
  count:
    per_slot: 1
```

For example, with `resource-query` (latest flux-sched master):
```bash
resource/utilities$ ./resource-query -p ALL:core -F pretty_simple -S CA -f jgf -P high -L cluster.json
INFO: Loading a matcher: CA
resource-query> match allocate test.yaml 
      ---k8scluster0[1:shared]
      ------rack0[1:shared]
      ---------ip-192-168-62-188.us-east-2.compute.internal6647[1:shared]
      ------------socket0[1:shared]
      ---------------core93[1:exclusive]
...
      ---------------core2[1:exclusive]
      ---------------core1[1:exclusive]
      ---------------core0[1:exclusive]
INFO: =============================
INFO: JOBID=1
INFO: RESOURCES=ALLOCATED
INFO: SCHEDULED AT=Now
INFO: =============================
resource-query>
```
However, with `hinode` and `lonode` (tested as well) the jobspec isn't matched:
```bash
$ ./resource-query -p ALL:core -F pretty_simple -S CA -f jgf -P hinode -L cluster.json
INFO: Loading a matcher: CA
resource-query> match allocate test.yaml 
INFO: =============================
INFO: No matching resources found
INFO: JOBID=1
INFO: =============================
resource-query> 
```

As a another wrinkle, a jobspec that requests 1 slot is matched 11 times successfully with `hinode`:
```bash
$ ./resource-query -p ALL:core -F pretty_simple -S CA -f jgf -P hinode -L cluster.json
INFO: Loading a matcher: CA
resource-query> match allocate test2.yaml
      ---k8scluster0[1:shared]
      ------rack0[1:shared]
      ---------ip-192-168-32-123.us-east-2.compute.internal2[1:shared]
      ------------socket0[1:shared]
      ---------------core93[1:exclusive]
      ---------------core92[1:exclusive]
...
      ---------------core2[1:exclusive]
      ---------------core1[1:exclusive]
      ---------------core0[1:exclusive]
INFO: =============================
INFO: JOBID=11
INFO: RESOURCES=ALLOCATED
INFO: SCHEDULED AT=Now
INFO: =============================
resource-query> match allocate test2.yaml
INFO: =============================
INFO: No matching resources found
INFO: JOBID=12
INFO: =============================
```
But matched 16 times (allocating all cores in the cluster) with `lonode`:
```bash
$ ./resource-query -p ALL:core -F pretty_simple -S CA -f jgf -P lonode -L cluster.json
resource-query> match allocate test2.yaml
...
INFO: =============================
INFO: JOBID=15
INFO: RESOURCES=ALLOCATED
INFO: SCHEDULED AT=Now
INFO: =============================
resource-query> m allocate test2.yaml
      ---k8scluster0[1:shared]
      ------rack0[1:shared]
      ---------ip-192-168-38-107.us-east-2.compute.internal2217[1:shared]
      ------------socket0[1:shared]
      ---------------core93[1:exclusive]
      ---------------core92[1:exclusive]
      ---------------core91[1:exclusive]
...
      ---------------core3[1:exclusive]
      ---------------core2[1:exclusive]
      ---------------core1[1:exclusive]
      ---------------core0[1:exclusive]
INFO: =============================
INFO: JOBID=16
INFO: RESOURCES=ALLOCATED
INFO: SCHEDULED AT=Now
INFO: =============================
resource-query> m allocate test2.yaml
INFO: =============================
INFO: No matching resources found
INFO: JOBID=17
INFO: =============================
resource-query>
```

To be explicit, here is the `test2.yaml` jobspec:
```YAML
version: 9999
resources:
- type: slot
  count: 1
  label: default
  with:
  - type: core
    count: 94
attributes:
  system:
    duration: 3600
tasks:
- command: [""]
  slot: default
  count:
    per_slot: 1
```

### PR DESCRIPTION
**Pull request by dongahn**
This PR adds fixes for the following problems.

With the recently added lonode[x]/hinode[x] match policies, each node's
numeric ID (e.g., node1231 where ID=1231) is used in our score calculation
of all of its containing resource vertices (e.g., cores, gpus...). When its ID
becomes high, however, a type coercion bug can result in an integer
overflow of the score, leading to a undefined behavior. In addition, when
a node's ID becomes even larger such that it can't fit into a signed
32-bit integer, our graph loading fails. While it is less likely we will have
such a huge node ID, it would be ideal to prevent that from happening at all.

-  Use `int64_t` to capure a score within our traverser to match the type
with the rest of the code that is involved in scoring;
- Change `std::atoi` to `std::atoll` to convert a large number string into a number
without raising an overflow exception within a hostname querying method
and adjust the callers within our readers accordingly; 
- Align the column of `t3027-resource-RV.t` test cases where HERE doc is
used such a way that a consistent tab-leading indentation helps with readability. 

Fixes #932.

### CODE REVIEW

**Comment by dongahn** [comment]
@milroy: Ok, I added one more test to cover an error branch and Codecov is happy now. This is ready for your quick review. Thank.s

File: resource/traversers/dfu_impl.cpp [hunk 1]
```diff
@@ -622,7 +622,7 @@ int dfu_impl_t::dom_slot (const jobmeta_t &meta, vtx_t u,
     qual_num_slots = cnt_slot (slot_shape, dfu_slot);
     for (unsigned int i = 0; i < qual_num_slots; ++i) {
         eval_egroup_t edg_group;
-        int score = MATCH_MET;
+        int64_t score = MATCH_MET;
```
Comment (jameshcorbett) [inline resource/traversers/dfu_impl.cpp:625]: General question not related to this particular change: is there a reason not to use `long long` instead of `int64_t`? Do you need it to be enforced as exactly 64 bits?

In this case I see that score is being incremented by ``eval_egroup_t.score`` which is int64_t so it makes sense here.

**Review by jameshcorbett — APPROVED** [review]
LGTM, I can't see any potential issues.

File: resource/traversers/dfu_impl.cpp (hunk 1 above)
Comment (dongahn) [reply resource/traversers/dfu_impl.cpp:625]: Thanks! Yeah, I could have used 'long long' as well. I just wanted to match the type across the board. For me, using an explicit type reduces my cognitive load but I understand there are other benefits to use implementation dependent types like 'long long`.
